### ISSUE TITLE
404 when attempting to view a resource that has proposed changes

### ISSUE THREAD

**Issue by Effervex** [aberonni/improvdb#62]
I'm finally getting stuck in an uploading the games/exercises I know.

However, I've found an error: when making proposed changes to an existing exercise, it is impossible to view the changes - it leads to a 404 error.

### Reproducible Example
1. Propose changes to an existing and accepted resource (e.g. "I am a Tree"). Save the changes
2. Navigate to User > My Proposed Resources
3. Select the entry for the changes existing resource. This leads to loading before a 404 message.

Curiously, this issue does not exist when changing your own proposed resource.

**Comment by aberonni** [comment]
Hey thanks for contributing and for reporting this issue! I will take a look and get back to you ASAP.

**Comment by Effervex** [comment]
Quick as lightning! Thanks!
