### ISSUE TITLE
Duplicate resources

### ISSUE THREAD

**Issue by Effervex** [aberonni/improvdb#63]
When proposing alterations to a newly created resource (before the resource is accepted), a new entry is created (which is also not yet accepted). However, upon acceptance of the resource(s), a separate duplicate resource is created for each.

This can be seen by viewing the current resources (as of this issue creation): there are two Director's Cuts and two Word Balls (with small differerences between each).

When making proposed changes to a not-yet-accepted resource, the list of pending proposed resources should only contain one entry (for the latest entry).

**Comment by Effervex** [comment]
Oh, this issue is actually bigger - it seems any resource that had a proposed change to it has created a separate entry (Bibbidy Bibbidy Bop, Pearls on a String, Switch Left).

**Comment by aberonni** [comment]
Will take a look ASAP. Thanks again for taking the time to report 🙏

**Comment by aberonni** [comment]
Should be all sorted now. Let me know if anything got lost in the process, but I don't think so :v:
