### ISSUE TITLE
Suggested additional Categories

### ISSUE THREAD

**Issue by Effervex** [aberonni/improvdb#66]
There are a few categories I'd like to include. Though perhaps it could even be possible to create entirely new ones on the fly?

* Guessing: a category for short-form games involving guessing.
* Director:  a category for short-form games involving a director.
* Audience Volunteer: a category for short-form games that may involve an audience volunteer.
* Constraints: a category for exercises and games that include a strong constraining element.

**Comment by aberonni** [comment]
Thanks for the suggestion! I've added your suggested categories. 

I purposefully avoided giving users the ability to generate categories. I think, for the filter to remain meaningful, it should be a finite list.
